"""empty message

Revision ID: 0ff0db171a89
Revises: 9d92ffc771ce
Create Date: 2024-02-08 11:06:10.353305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff0db171a89'
down_revision = '9d92ffc771ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_express', sa.Boolean(), nullable=False))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('has_express')

    # ### end Alembic commands ###
